### ISSUE TITLE
Warning about parentheses after method name

### ISSUE THREAD

**Issue by dburkat** [josephruscio/aggregate#13]
I'm using the aggregate gem with jruby-9.4.2.0 and it is giving me the warning below when bundler loads the gem:
```warning: parentheses after method name is interpreted as an argument list, not a decomposed argument```

There are 3 method definitions where there is a space after the name:
- https://github.com/josephruscio/aggregate/blob/v0.2.3/lib/aggregate.rb#L29  
- https://github.com/josephruscio/aggregate/blob/v0.2.3/lib/aggregate.rb#L207
- https://github.com/josephruscio/aggregate/blob/v0.2.3/lib/aggregate.rb#L234

Not a big deal, but warning are annoying so figured I should point this out.

**Comment by nextmat** [comment]
Thanks for the report - this should be fixed in v0.2.4

Closing, but feel free to reopen if you run into issues with the new release.
